name: Repo Dispatch
on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
    inputs:
      message:
        description: name of package to update (canvas, api1, etc)
        required: true
    
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      - run: echo ${{ github.event.inputs.message}}
